const color = require('../color.js')

editorColors = {
  transparent: '#00000000',
  actBg: '#193036',
  sidebarBg: '#132430',
  ghostText: '#376D7A',
  selection: color.red + '55',
  inactSelection: color.gray + '45',
  editorBg: '#0F1923',
  findRangeHighlightBg: '#000d0c' + '33',
  darkBG400: '#455a64',
  darkBG300: '#38494d',
  darkBG200: '#262d38',
  darkBG100: '#1e3242',
  darkBG50: '#182835',
  darkBG40: '#172734',
  darkBG30: '#17252a',
  darkBG25: '#162025',
  darkBG20: '#151f24',
  darkBG10: '#132330',
  darkBG00: '#0b181e',
  darkBG01: '#0e1720',
}

merge = {
  currentHeaderBG: '#00897b',
  currentContentBG: '#00695c',
  incomingHeaderBG: '#00acc1',
  incomingContentBG: '#00838f',
  commonHeaderBG: '#546e7a',
  commonContentBG: '#37474f',
}

module.exports = {
  'editorGhostText.foreground': editorColors.ghostText,
  foreground: color.lightGray,
  focusBorder: color.darkGray,
  'progressBar.background': color.darkGray,
  'selection.background': editorColors.selection,
  'scrollbar.shadow': editorColors.darkBG30,
  'activityBar.foreground': color.lightGray,
  'activityBar.background': editorColors.actBg,
  'activityBar.inactiveForeground': color.darkGray,
  'activityBarBadge.foreground': color.lightGray,
  'activityBarBadge.background': color.red,
  'button.background': color.red + 'dc',
  'button.foreground': color.white,
  'button.hoverBackground': color.red,
  'textLink.foreground': color.red + 'dc',
  'textLink.activeForeground': color.red,
  'button.secondaryForeground': color.lightGray,
  'button.secondaryBackground': editorColors.darkBG300,
  'button.secondaryHoverBackground': editorColors.darkBG400,
  'editor.foreground': color.lightGray,
  'editor.background': editorColors.editorBg,
  'editorLineNumber.foreground': color.darkGray,
  'editorLineNumber.activeForeground': color.red,
  'editorCursor.foreground': color.red,
  'editorCursor.background': color.lightGray,
  'editor.selectionBackground': editorColors.selection,
  'editor.inactiveSelectionBackground':
    editorColors.inactSelection,
  'editorWhitespace.foreground': color.lightGray + '66',
  'editor.selectionHighlightBackground': color.red + '48',
  'editor.selectionHighlightBorder': color.red,
  'editor.findMatchBackground': color.red + '48',
  'editor.findMatchBorder': color.red,
  'editor.findMatchHighlightBackground': color.red + '66',
  'editor.findRangeHighlightBackground':
    editorColors.findRangeHighlightBg,
  'editor.rangeHighlightBackground': editorColors.darkBG100,
  'editor.hoverHighlightBackground': color.red + '40',
  'editor.wordHighlightStrongBackground': color.red + '40',
  'editor.wordHighlightBackground': color.red + '48',
  'editor.wordHighlightStrongBorder': color.red,
  'editor.lineHighlightBackground': editorColors.darkBG50,
  'editorLink.activeForeground': color.cyan,
  'editorIndentGuide.background': color.darkGray,
  'editorIndentGuide.activeBackground': color.lightGray,
  'editorRuler.foreground': color.darkGray,
  'editorBracketMatch.background': color.red + '66',
  'editorBracketMatch.border': color.red,
  'editor.foldBackground': color.red + '1e',
  'editorOverviewRuler.border': color.darkGray + '66',
  'editorError.foreground': color.red,
  'editorWarning.foreground': color.orange,
  'editorInfo.foreground': color.blue,
  'editorGutter.background': editorColors.editorBg,
  'editorGutter.addedBackground': color.teal,
  'editorGutter.modifiedBackground': color.yellow,
  'editorGutter.deletedBackground': color.red,
  'editorGutter.foldingControlForeground': color.darkGray,
  'editorGutter.foldingControlHoverForeground':
    color.lightGray,
  'editorCodeLens.foreground': color.darkGray,
  'editorGroup.border': color.darkGray,
  'editorGroupHeader.border': editorColors.transparent,
  'diffEditor.insertedTextBackground': color.green + '33',
  'diffEditor.removedTextBackground': color.red + '33',
  'diffEditor.border': color.darkGray,
  'editorMarkerNavigation.background': editorColors.actBg,
  'editorMarkerNavigationError.background': color.red,
  'editorMarkerNavigationWarning.background': color.yellow,
  'editorMarkerNavigationInfo.background': color.blue,
  'merge.currentHeaderBackground': merge.currentHeaderBG,
  'merge.currentContentBackground': merge.currentContentBG,
  'merge.incomingHeaderBackground': merge.incomingHeaderBG,
  'merge.incomingContentBackground':
    merge.incomingContentBG,
  'merge.commonHeaderBackground': merge.commonHeaderBG,
  'merge.commonContentBackground': merge.commonContentBG,
  'editorSuggestWidget.background': editorColors.darkBG40,
  'editorSuggestWidget.border': color.darkGray + '70',
  'editorSuggestWidget.foreground': color.darkGray,
  'editorSuggestWidget.highlightForeground': color.red,
  'editorSuggestWidget.selectedBackground':
    editorColors.darkBG100,
  'editorHoverWidget.foreground': color.darkGray,
  'editorHoverWidget.background': editorColors.darkBG40,
  'editorHoverWidget.border': color.darkGray + '70',
  'peekView.border': color.darkGray,
  'peekViewEditor.background': editorColors.darkBG200,
  'peekViewEditorGutter.background': editorColors.darkBG200,
  'peekViewEditor.matchHighlightBackground':
    color.red + '66',
  'peekViewEditor.matchHighlightBorder': color.red,
  'peekViewResult.background': editorColors.darkBG40,
  'peekViewResult.fileForeground': color.darkGray,
  'peekViewResult.lineForeground': color.darkGray,
  'peekViewResult.matchHighlightBackground':
    color.red + '66',
  'peekViewResult.selectionBackground':
    editorColors.darkBG100,
  'peekViewResult.selectionForeground': color.lightGray,
  'peekViewTitle.background': editorColors.darkBG40,
  'peekViewTitleDescription.foreground': color.darkGray,
  'peekViewTitleLabel.foreground': color.lightGray,
  'widget.shadow': editorColors.darkBG00 + '66',
  'editorWidget.foreground': color.lightGray,
  'editorWidget.background': editorColors.darkBG40,
  'pickerGroup.border': editorColors.darkBG300,
  'pickerGroup.foreground': color.red,
  'editorWidget.resizeBorder': color.red,
  'debugToolBar.background': editorColors.darkBG40,
  'debugToolBar.border': color.darkGray + '70',
  'notifications.foreground': color.lightGray,
  'notifications.background': editorColors.darkBG40,
  'notifications.border': color.darkGray + '70',
  'notificationLink.foreground': color.red,
  'notificationsErrorIcon.foreground': color.red,
  'notificationsWarningIcon.foreground': color.yellow,
  'notificationsInfoIcon.foreground': color.blue,
  'notificationCenterHeader.foreground': color.lightGray,
  'notificationCenterHeader.background': editorColors.actBg,
  'notificationCenter.border': color.darkGray + '70',
  'sideBar.background': editorColors.sidebarBg,
  'sideBar.foreground': color.darkGray,
  'sideBarSectionHeader.background': editorColors.actBg,
  'sideBarSectionHeader.foreground': color.lightGray,
  'sideBarSectionHeader.border': color.lightGray + '15',
  'sideBarTitle.foreground': color.lightGray,
  'list.inactiveSelectionBackground':
    editorColors.darkBG100,
  'list.inactiveSelectionForeground': color.gray,
  'list.hoverForeground': color.lightGray,
  'list.hoverBackground': editorColors.transparent,
  'list.activeSelectionBackground': editorColors.darkBG100,
  'list.activeSelectionForeground': color.lightGray,
  'list.dropBackground': editorColors.darkBG20,
  'list.highlightForeground': color.lightGray,
  'list.focusBackground': editorColors.darkBG100,
  'list.focusForeground': color.lightGray,
  'list.focusOutline': editorColors.transparent,
  'listFilterWidget.background': color.lightGray,
  'listFilterWidget.noMatchesOutline': color.red,
  'tree.indentGuidesStroke': color.darkGray,
  'statusBar.foreground': color.lightGray,
  'statusBar.background': editorColors.editorBg,
  'statusBar.border': color.darkGray + '70',
  'statusBarItem.hoverBackground': color.lightGray + '33',
  'statusBar.debuggingBackground': color.red,
  'statusBar.debuggingForeground': color.white,
  'statusBar.noFolderBackground': color.blue,
  'statusBar.noFolderForeground': color.white,
  'statusBarItem.remoteBackground': editorColors.actBg,
  'statusBarItem.remoteForeground': color.lightGray,
  'titleBar.activeBackground': editorColors.actBg,
  'titleBar.activeForeground': color.lightGray,
  'titleBar.border': color.darkGray + '70',
  'titleBar.inactiveBackground': editorColors.actBg,
  'titleBar.inactiveForeground': color.darkGray,
  'menubar.selectionForeground': color.lightGray,
  'menubar.selectionBackground': editorColors.darkBG40,
  'menu.foreground': color.darkGray,
  'menu.background': editorColors.darkBG40,
  'menu.selectionForeground': color.lightGray,
  'menu.selectionBackground': editorColors.darkBG100,
  'menu.selectionBorder': editorColors.transparent,
  'menu.separatorBackground': color.darkGray,
  'menu.border': color.darkGray + '30',
  'quickInput.foreground': color.darkGray,
  'quickInputList.focusBackground': editorColors.darkBG100,
  'quickInputList.focusForeground': color.lightGray,
  'input.background': editorColors.darkBG100,
  'input.foreground': color.lightGray,
  'input.placeholderForeground': color.darkGray,
  'inputOption.activeBackground': color.darkGray,
  'inputOption.activeForeground': color.lightGray,
  'checkbox.border': color.red,
  'checkbox.foreground': color.red,
  'panel.background': editorColors.editorBg,
  'panel.border': color.darkGray,
  'panelTitle.activeBorder': color.red,
  'panelTitle.activeForeground': color.lightGray,
  'panelTitle.inactiveForeground': color.darkGray,
  'terminal.selectionBackground': color.red + '33',
  'terminalCursor.foreground': color.lightGray,
  'terminalCursor.background': color.red,
  'badge.background': color.red,
  'badge.foreground': color.white,
  'terminal.border': color.darkGray,
  'terminal.foreground': color.lightGray,
  'terminal.ansiWhite': color.lightGray,
  'terminal.ansiBrightWhite': color.white,
  'terminal.ansiBlack': color.darkGray,
  'terminal.ansiBrightBlack': color.gray,
  'terminal.ansiBlue': color.blue,
  'terminal.ansiBrightBlue': color.blue,
  'terminal.ansiCyan': color.cyan,
  'terminal.ansiBrightCyan': color.sky,
  'terminal.ansiGreen': color.teal,
  'terminal.ansiBrightGreen': color.teal,
  'terminal.ansiMagenta': color.purple,
  'terminal.ansiBrightMagenta': color.pink,
  'terminal.ansiRed': color.red,
  'terminal.ansiBrightRed': color.brightRed,
  'terminal.ansiYellow': color.yellow,
  'terminal.ansiBrightYellow': color.orange,
  'editorGroupHeader.tabsBackground': editorColors.darkBG01,
  'editorGroupHeader.tabsBorder': editorColors.transparent,
  'tab.activeForeground': color.lightGray,
  'tab.activeBackground': editorColors.editorBg,
  'tab.activeBorderTop': color.red,
  'tab.inactiveBackground': editorColors.darkBG40,
  'tab.inactiveForeground': color.darkGray,
  'tab.hoverForeground': color.lightGray,
  'breadcrumb.background': editorColors.editorBg,
  'breadcrumb.foreground': color.darkGray,
  'breadcrumb.focusForeground': color.lightGray,
  'scrollbarSlider.background': color.red + '33',
  'scrollbarSlider.hoverBackground': color.red + '66',
  'scrollbarSlider.activeBackground': color.red + '99',
  'gitDecoration.addedResourceForeground': color.teal,
  'gitDecoration.conflictingResourceForeground': color.sky,
  'gitDecoration.deletedResourceForeground': color.red,
  'gitDecoration.ignoredResourceForeground': color.darkGray,
  'gitDecoration.modifiedResourceForeground': color.yellow,
  'gitDecoration.stageDeletedResourceForeground':
    color.orange,
  'gitDecoration.stageModifiedResourceForeground':
    color.orange,
  'gitDecoration.submoduleResourceForeground': color.blue,
  'gitDecoration.untrackedResourceForeground': color.green,
  'settings.headerForeground': color.lightGray,
  'settings.modifiedItemIndicator': color.red,
  'settings.dropdownBackground': editorColors.darkBG100,
  'settings.dropdownForeground': color.lightGray,
  'settings.dropdownBorder': color.darkGray,
  'settings.dropdownListBorder': editorColors.transparent,
  'settings.checkboxBackground': editorColors.darkBG100,
  'settings.rowHoverBackground': editorColors.darkBG40,
  'settings.focusedRowBackground': editorColors.darkBG10,
  'settings.focusedRowBorder': editorColors.transparent,
  'minimapGutter.addedBackground': color.teal,
  'minimapGutter.deletedBackground': color.red,
  'minimapGutter.modifiedBackground': color.sky,
  'walkThrough.embeddedEditorBackground':
    editorColors.actBg,
  'textPreformat.foreground': color.lightGray,
  'textBlockQuote.border': color.darkGray,
  'welcomePage.buttonHoverBackground': color.cyan,
  'editorBracketHighlight.foreground1': color.sky,
  'editorBracketPairGuide.activeBackground1': color.sky,
  'editorBracketHighlight.foreground2': color.pink,
  'editorBracketPairGuide.activeBackground2': color.pink,
  'editorBracketHighlight.foreground3': color.red,
  'editorBracketPairGuide.activeBackground3': color.red,
  'editorBracketHighlight.foreground4': color.yellow,
  'editorBracketPairGuide.activeBackground4': color.yellow,
  'editorBracketHighlight.foreground5': color.teal,
  'editorBracketPairGuide.activeBackground5': color.teal,
  'editorBracketHighlight.foreground6': color.orange,
  'editorBracketPairGuide.activeBackground6': color.orange,
  'list.focusHighlightForeground': color.red,
  'toolbar.hoverBackground': color.lightGray + '11',
  'toolbar.activeBackground': color.red,
  'icon.foreground': color.lightGray,
  'dropdown.background': editorColors.darkBG100,
  'dropdown.foreground': color.lightGray,
  'dropdown.border': color.darkGray + '70',
  'minimap.background': editorColors.editorBg,
  'statusBarItem.activeBackground': color.red,
  'breadcrumb.activeSelectionForeground': color.lightGray,
  'debugExceptionWidget.border': color.darkGray + '70',
  'debugExceptionWidget.background': editorColors.darkBG40,
}
