const color = require('../colors/primaryColors.js');
const { shades, editorColors, merge } = require('../colors/addtionalColors');

module.exports = {
  foreground: color.lightGray,
  focusBorder: color.darkGray,
  'selection.background': editorColors.selection,
  'widget.shadow': shades.shade900 + '66',
  'icon.foreground': color.lightGray,

  /* 
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\ Everything down below is taken from ⤵                    \\
  \\ https://code.visualstudio.com/api/references/theme-color \\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  */

  /* ________ window border ________ */
  // 'window.activeBorder': '',
  // 'window.inActiveBorder': '',

  /* ________ text colors ________ */
  'textBlockQuote.background': shades.shade500,
  'textBlockQuote.border': color.darkGray,
  'textCodeBlock.background': shades.shade800,
  'textLink.activeForeground': editorColors.linkAct,
  'textLink.foreground': editorColors.link,
  'textPreformat.foreground': shades.foreground,
  'textSeparator.foreground': color.darkGray,

  /* ________ action colors ________ */
  'toolbar.hoverBackground': shades.shade400 + 'aa',
  // 'toolbar.hoverOutline': shades.primary,
  'toolbar.activeBackground': shades.shade300,

  /* ________ button control ________ */
  'button.background': shades.primary,
  'button.foreground': color.white,
  // 'button.border': '',
  'button.separator': color.lightGray + '66',
  'button.hoverBackground': shades.primary,
  'button.secondaryForeground': shades.foreground,
  'button.secondaryBackground': shades.shade100,
  'button.secondaryHoverBackground': shades.shade50,
  'checkbox.background': shades.primary,
  'checkbox.foreground': color.white,
  'checkbox.border': shades.primary,

  /* ________ dropdown control ________ */
  'dropdown.background': editorColors.inputBG,
  'dropdown.listBackground': shades.shade600,
  'dropdown.border': editorColors.border,
  'dropdown.foreground': shades.foreground,

  /* ________ input control ________ */
  'input.background': editorColors.inputBG,
  'input.border': editorColors.border,
  'input.foreground': shades.foreground,
  'input.placeholderForeground': color.darkGray,
  'inputOption.activeBackground': color.darkGray,
  // 'inputOption.activeBorder': '',
  'inputOption.activeForeground': shades.foreground,
  // 'inputOption.hoverBackground': '',
  'inputValidation.errorBackground': editorColors.error + '45',
  'inputValidation.errorForeground': shades.foreground,
  'inputValidation.errorBorder': editorColors.error,
  'inputValidation.infoBackground': editorColors.info + '45',
  'inputValidation.infoForeground': shades.foreground,
  'inputValidation.infoBorder': editorColors.info,
  'inputValidation.warningBackground': editorColors.warning + '45',
  'inputValidation.warningForeground': shades.foreground,
  'inputValidation.warningBorder': editorColors.warning,

  /* ________ scrollbar control ________ */
  'scrollbar.shadow': editorColors.shadow,
  'scrollbarSlider.background': editorColors.scroll,
  'scrollbarSlider.hoverBackground': editorColors.scrollHover,
  'scrollbarSlider.activeBackground': editorColors.scrollActive,

  /* ________ badge control ________ */
  'badge.background': shades.primary,
  'badge.foreground': color.white,

  /* ________ progress bar ________ */
  'progressBar.background': shades.primary,

  /* ________ lists and trees ________ */
  'list.activeSelectionBackground': editorColors.itemActBG,
  'list.activeSelectionForeground': editorColors.itemActFG,
  // 'list.activeSelectionIconForeground': '',
  'list.inactiveSelectionBackground': editorColors.itemInactBG,
  'list.inactiveSelectionForeground': editorColors.itemInactFG,
  // 'list.inactiveSelectionIconForeground': '',
  'list.hoverBackground': editorColors.itemHoverBG,
  'list.hoverForeground': editorColors.itemHoverFG,
  'list.dropBackground': editorColors.drop,
  'list.focusBackground': editorColors.sidebarBG,
  'list.focusForeground': color.white,
  'list.focusHighlightForeground': shades.primary,
  'list.focusOutline': shades.transparent,
  // 'list.focusAndSelectionOutline': '',
  'list.highlightForeground': shades.foreground,
  /* 
    /////////////////
    //  this far  //
    ////////////////
  */
  // 'list.inactiveFocusBackground': '',
  // 'list.inactiveFocusOutline': '',
  // 'list.invalidItemForeground': '',
  // 'list.errorForeground': '',
  // 'list.warningForeground': '',
  'listFilterWidget.background': editorColors.modal,
  // 'listFilterWidget.outline': '',
  'listFilterWidget.noMatchesOutline': shades.primary,
  // 'list.filterMatchBackground': '',
  // 'list.filterMatchBorder': '',
  // 'list.deemphasizedForegrou': '',
  'tree.indentGuidesStroke': shades.foreground,
  // 'tree.tableColumnsBorder': '',
  // 'tree.tableOddRowsBackground': '',

  /* ________ activity bar ________ */
  'activityBar.background': editorColors.activityBarBG,
  'activityBar.dropBorder': shades.primary,
  'activityBar.foreground': editorColors.activityBarFG,
  'activityBar.inactiveForeground': editorColors.activityBarInactFG,
  'activityBar.border': editorColors.activityBarBorder,
  'activityBarBadge.background': shades.primary,
  'activityBarBadge.foreground': shades.foreground,
  // 'activityBar.activeBorder': '',
  // 'activityBar.activeBackground': '',
  // 'activityBar.activeFocusBorder: '',

  /* ________ side bar ________ */
  'sideBar.background': editorColors.sidebarBG,
  'sideBar.foreground': editorColors.sidebarFG,
  'sideBar.border': editorColors.sidebarBorder,
  // 'sideBar.dropBackground': '',
  'sideBarTitle.foreground': shades.foreground,
  'sideBarSectionHeader.background': editorColors.sidebarBG,
  'sideBarSectionHeader.foreground': shades.foreground,
  'sideBarSectionHeader.border': editorColors.border,

  /* ________ mini map ________ */
  'minimap.findMatchHighlight': shades.primary + '80',
  'minimap.selectionHighlight': shades.primary + 'bg',
  'minimap.errorHighlight': editorColors.error + 'dd',
  'minimap.warningHighlight': editorColors.warning + 'dd',
  'minimap.background': editorColors.minimapBG,
  'minimap.selectionOccurrenceHighlight': color.green + '80',
  'minimap.foregroundOpacity': shades.shade000 + 'c0',
  'minimapSlider.background': editorColors.scroll,
  'minimapSlider.hoverBackground': editorColors.scrollHover,
  'minimapSlider.activeBackground': editorColors.scrollActive,
  'minimapGutter.addedBackground': editorColors.added,
  'minimapGutter.deletedBackground': editorColors.deleted,
  'minimapGutter.modifiedBackground': editorColors.modified,

  /* ________ editor groups & tabs ________ */
  'editorGroup.border': shades.primary + '66',
  'editorGroup.dropBackground': shades.shade100 + '35',
  // 'editorGroupHeader.noTabsBackground': '',
  'editorGroupHeader.tabsBackground': shades.shade900,
  'editorGroupHeader.tabsBorder': shades.transparent,
  'editorGroupHeader.border': shades.transparent,
  // 'editorGroup.emptyBackground': '',
  // 'editorGroup.focusedEmptyBackground': '',
  // 'editorGroup.dropIntoPromptForeground': '',
  // 'editorGroup.dropIntoPromptBackground': '',
  // 'editorGroup.dropIntoPromptBorder': '',
  'tab.activeBackground': editorColors.editorBG,
  // 'tab.unfocusedActiveBackground': '',
  'tab.activeForeground': shades.foreground,
  // 'tab.unfocusedActiveForeground': '',
  'tab.inactiveBackground': shades.shade800,
  // 'tab.unfocusedInactiveBackground': '',
  'tab.inactiveForeground': color.darkGray,
  // 'tab.unfocusedInactiveForeground': '',
  // 'tab.border': '',
  // 'tab.activeBorder': '',
  // 'tab.unfocusedActiveBorder': '',
  'tab.activeBorderTop': shades.primary, // same 3 variants are available
  'tab.lastPinnedBorder': shades.transparent,
  // 'tab.hoverBackground': '',
  // 'tab.unfocusedHoverBackground': '',
  'tab.hoverForeground': shades.foreground,
  // 'tab.unfocusedHoverForeground': '',
  // 'tab.hoverBorder': '',
  // 'tab.unfocusedHoverBorder': '',
  // 'tab.activeModifiedBorder': '',
  // 'tab.inactiveModifiedBorder': '',
  // 'tab.unfocusedActiveModifiedBorder': '',
  // 'tab.unfocusedInactiveModifiedBorder': '',
  // 'editorpane.background': '',
  // 'sideBySideEditor.horizontalBorder' : '',
  // 'sideBySideEditor.verticalBorder' : '',

  /* ________ editor colors ________ */
  'editor.background': editorColors.editorBG,
  'editor.foreground': shades.foreground,
  'editorLineNumber.foreground': color.darkGray,
  'editorLineNumber.activeForeground': shades.primary,
  'editorCursor.background': shades.foreground,
  'editorCursor.foreground': shades.primary,
  'editor.selectionBackground': editorColors.selection,
  // 'editor.selectionForeground': '',
  'editor.inactiveSelectionBackground': editorColors.inactSelection,
  'editor.selectionHighlightBackground': editorColors.highlight,
  'editor.selectionHighlightBorder': shades.primary,
  'editor.wordHighlightBackground': editorColors.highlight,
  'editor.wordHighlightStrongBorder': shades.primary,
  'editor.wordHighlightStrongBackground': editorColors.highlight,
  'editor.findMatchBackground': editorColors.highlight,
  'editor.findMatchHighlightBackground': editorColors.fmHighlight,
  'editor.findRangeHighlightBackground': editorColors.frHighlight,
  'editor.findMatchBorder': shades.primary,
  'editor.findMatchHighlightBorder': editorColors.border,
  // 'editor.findRangeHighlightBorder': '',
  // 'searchEditor.findMatchBackground' : '',
  // 'searchEditor.findMatchBorder': '',
  // 'searchEditor.textInputBorder' : '',
  'editor.hoverHighlightBackground': editorColors.hvHighlight,
  'editor.lineHighlightBackground': shades.shade600,
  // 'editor.lineHighlightBorder': '',
  // 'editor.unicodeHighlightBackground': '',
  // 'editor.unicodeHighlightBorder': '',
  'editorLink.activeForeground': editorColors.linkAct,
  'editor.rangeHighlightBackground': shades.shade800,
  // 'editor.rangeHighlightBorder': '',
  // 'editor.symbolHighlightBackground': '',
  // 'editor.symbolHighlightBorder': '',
  'editorWhitespace.foreground': shades.foreground + '66',
  'editorIndentGuide.background': color.darkGray,
  'editorIndentGuide.activeBackground': shades.foreground,
  // 'editorInlayHint.background' : '',
  // 'editorInlayHint.foreground' : '',
  // 'editorInlayHint.typeForeground' : '',
  // 'editorInlayHint.typeBackground' : '',
  // 'editorInlayHint.parameterForeground' : '',
  // 'editorInlayHint.parameterBackground' : '',
  'editorRuler.foreground': color.darkGray,
  // 'editor.linkedEditingBackground': '',
  'editorCodeLens.foreground': color.darkGray,
  // 'editorLightBulb.foreground' : '',
  // 'editorLightBulbAutoFix.foreground' : '',
  'editorBracketMatch.background': shades.primary + '66',
  'editorBracketMatch.border': shades.primary,
  'editorBracketHighlight.foreground1': color.sky,
  'editorBracketHighlight.foreground2': color.pink,
  'editorBracketHighlight.foreground3': color.red,
  'editorBracketHighlight.foreground4': color.yellow,
  'editorBracketHighlight.foreground5': color.teal,
  'editorBracketHighlight.foreground6': color.orange,
  'editorBracketHighlight.unexpectedBracket.foreground': shades.foreground,
  'editorBracketPairGuide.activeBackground1': color.sky,
  'editorBracketPairGuide.activeBackground2': color.pink,
  'editorBracketPairGuide.activeBackground3': color.red,
  'editorBracketPairGuide.activeBackground4': color.yellow,
  'editorBracketPairGuide.activeBackground5': color.teal,
  'editorBracketPairGuide.activeBackground6': color.orange,
  // 'editorBracketPairGuide.background1': '',
  // 'editorBracketPairGuide.background2': '',
  // 'editorBracketPairGuide.background3': '',
  // 'editorBracketPairGuide.background4': '',
  // 'editorBracketPairGuide.background5': '',
  // 'editorBracketPairGuide.background6': '',
  'editor.foldBackground': shades.primary + '1e',
  // 'editorOverviewRuler.background': '',
  'editorOverviewRuler.border': color.darkGray + '66',
  // 'editorOverviewRuler.findMatchForeground': '',
  // 'editorOverviewRuler.rangeHighlightForeground': '',
  // 'editorOverviewRuler.selectionHighlightForeground': '',
  // 'editorOverviewRuler.wordHighlightForeground': '',
  // 'editorOverviewRuler.wordHighlightStrongForeground': '',
  // 'editorOverviewRuler.modifiedForeground': '',
  // 'editorOverviewRuler.addedForeground': '',
  // 'editorOverviewRuler.deletedForeground': '',
  // 'editorOverviewRuler.errorForeground': '',
  // 'editorOverviewRuler.warningForeground': '',
  // 'editorOverviewRuler.infoForeground': '',
  // 'editorOverviewRuler.bracketMatchForeground': '',

  /* --- errors & warnings --- */
  'editorError.foreground': editorColors.error,
  // 'editorError.border': '',
  // 'editorError.background': '',
  'editorWarning.foreground': editorColors.warning,
  // 'editorWarning.border': '',
  // 'editorWarning.background': '',
  'editorInfo.foreground': editorColors.info,
  // 'editorInfo.border': '',
  // 'editorInfo.backgground': '',
  // 'editorHint.foreground' : '',
  // 'editorHint.border' : '',
  // 'problemsErrorIcon.foreground' : '',
  // 'problemsWarningIcon.foreground' : '',
  // 'problemsInfoIcon.foreground' : '',

  /* --- unused source code --- */
  //  'editorUnnecessaryCode.border' : '',
  // 'editorUnnecessaryCode.opacity' : '',

  /* --- the gutter --- */
  'editorGutter.background': editorColors.editorBG,
  'editorGutter.modifiedBackground': editorColors.modified,
  'editorGutter.addedBackground': editorColors.added,
  'editorGutter.deletedBackground': editorColors.deleted,
  // 'editorGutter.commentRangeForeground': '',
  'editorGutter.foldingControlForeground': color.darkGray,

  /* --- comments widget --- */
  // 'editorCommentsWidget.resolvedBorder' : '',
  // 'editorCommentsWidget.unresolvedBorder' : '',
  // 'editorCommentsWidget.rangeBackground' : '',
  // 'editorCommentsWidget.rangeBorder' : '',
  // 'editorCommentsWidget.rangeActiveBackground' : '',
  // 'editorCommentsWidget.rangeActiveBorder' : '',

  /* ________ diff editor colors ________ */
  'diffEditor.insertedTextBackground': color.green + '33',
  // "diffEditor.insertedTextBorder": '',
  'diffEditor.removedTextBackground': color.red + '33',
  // "diffEditor.removedTextBorder": '',
  'diffEditor.border': color.darkGray,
  // "diffEditor.diagonalFill": '',
  // "diffEditor.insertedLineBackground": '',
  // "diffEditor.removedLineBackground": '',
  // "diffEditorGutter.insertedLineBackground": '',
  // "diffEditorGutter.removedLineBackground": '',
  // "diffEditorOverview.insertedForeground": '',
  // "diffEditorOverview.removedForeground": '',

  /* ________ editor widget colors ________ */
  'editorWidget.foreground': color.lightGray,
  'editorWidget.background': shades.shade400,
  'editorWidget.border': color.red,
  'editorWidget.resizeBorder': color.red,
  'editorSuggestWidget.background': shades.shade400,
  'editorSuggestWidget.border': color.darkGray + '70',
  'editorSuggestWidget.foreground': color.darkGray,
  // "editorSuggestWidget.focusHighlightForeground": '',
  'editorSuggestWidget.highlightForeground': color.red,
  'editorSuggestWidget.selectedBackground': shades.shade800,
  // "editorSuggestWidget.selectedForeground": ''
  // "editorSuggestWidget.selectedIconForeground": ''
  // "editorSuggestWidgetStatus.foreground": '',
  'editorHoverWidget.foreground': color.darkGray,
  'editorHoverWidget.background': shades.shade400,
  'editorHoverWidget.border': color.darkGray + '70',
  // "editorHoverWidget.highlightForeground": '',
  // "editorHoverWidget.statusBarBackground": '',
  // "editorGhostText.border": '',
  // "editorGhostText.background": '',
  'editorGhostText.foreground': shades.shade250,
  // "editorStickyScroll.background": '',
  // "editorStickyScrollHover.background": '',
  'debugExceptionWidget.background': shades.shade400,
  'debugExceptionWidget.border': color.darkGray + '70',
  'editorMarkerNavigation.background': editorColors.actBg,
  'editorMarkerNavigationError.background': color.red,
  'editorMarkerNavigationWarning.background': color.yellow,
  'editorMarkerNavigationInfo.background': color.blue,
  // "editorMarkerNavigationError.headerBackground": '',
  // "editorMarkerNavigationWarning.headerBackground": '',
  // "editorMarkerNavigationInfo.headerBackground": '',

  /* ________ peek view colors ________ */
  'peekView.border': color.darkGray,
  'peekViewEditor.background': shades.shade7000,
  'peekViewEditorGutter.background': shades.shade7000,
  'peekViewEditor.matchHighlightBackground': color.red + '66',
  'peekViewEditor.matchHighlightBorder': color.red,
  'peekViewResult.background': shades.shade400,
  'peekViewResult.fileForeground': color.darkGray,
  'peekViewResult.lineForeground': color.darkGray,
  'peekViewResult.matchHighlightBackground': color.red + '66',
  'peekViewResult.selectionBackground': shades.shade800,
  'peekViewResult.selectionForeground': color.lightGray,
  'peekViewTitle.background': shades.shade400,
  'peekViewTitleDescription.foreground': color.darkGray,
  'peekViewTitleLabel.foreground': color.lightGray,

  /* ________ merge conflicts colors ________ */
  'merge.currentHeaderBackground': merge.currentHeaderBG,
  'merge.currentContentBackground': merge.currentContentBG,
  'merge.incomingHeaderBackground': merge.incomingHeaderBG,
  'merge.incomingContentBackground': merge.incomingContentBG,
  // "merge.border": '',
  'merge.commonHeaderBackground': merge.commonHeaderBG,
  'merge.commonContentBackground': merge.commonContentBG,
  // "editorOverviewRuler.currentContentForeground": '',
  // "editorOverviewRuler.incomingContentForeground": '',
  // "editorOverviewRuler.commonContentForeground": '',
  // "mergeEditor.change.background": '',
  // "mergeEditor.change.word.background": '',
  // "mergeEditor.conflict.unhandledUnfocused.border": '',
  // "mergeEditor.conflict.unhandledFocused.border": '',
  // "mergeEditor.conflict.handledUnfocused.border": '',
  // "mergeEditor.conflict.handledFocused.border": '',
  // "mergeEditor.conflict.handled.minimapOverViewRuler": '',
  // "mergeEditor.conflict.unhandled.minimapOverViewRuler": '',
  // "mergeEditor.conflictingLines.background": '',
  // "mergeEditor.changeBase.background": '',
  // "mergeEditor.changeBase.word.background": '',
  // "mergeEditor.conflict.input1.background": '',
  // "mergeEditor.conflict.input2.background": '',

  /* ________ panel colors ________ */
  'panel.background': editorColors.editorBG,
  'panel.border': color.darkGray,
  // "panel.dropBorder": '',
  'panelTitle.activeBorder': color.red,
  'panelTitle.activeForeground': color.lightGray,
  'panelTitle.inactiveForeground': color.darkGray,
  // "panelInput.border": '',
  // "panelSection.border": '',
  // "panelSection.dropBackground": '',
  // "panelSectionHeader.background": '',
  // "panelSectionHeader.foreground": '',
  // "panelSectionHeader.border": '',

  /* ________ status bar colors ________ */
  'statusBar.background': editorColors.editorBG,
  'statusBar.foreground': color.lightGray,
  'statusBar.border': color.darkGray + '70',
  'statusBar.debuggingForeground': color.white,
  // "statusBar.debuggingBorder": '',
  'statusBar.debuggingBackground': color.red,
  'statusBar.noFolderForeground': color.white,
  // "statusBar.noFolderBorder": '',
  'statusBar.noFolderBackground': color.blue,
  'statusBarItem.activeBackground': color.red,
  'statusBarItem.hoverBackground': color.lightGray + '33',
  // "statusBarItem.prominentForeground": '',
  // "statusBarItem.prominentBackground": '',
  // "statusBarItem.prominentHoverBackground": '',
  'statusBarItem.remoteBackground': editorColors.actBg,
  'statusBarItem.remoteForeground': color.lightGray,
  // "statusBarItem.errorBackground": '',
  // "statusBarItem.errorForeground": '',
  // "statusBarItem.warningBackground": '',
  // "statusBarItem.warningForeground": '',
  // "statusBarItem.compactHoverBackground": '',
  // "statusBarItem.focusBorder": '',
  // "statusBar.focusBorder": '',

  /* ________ title bar colors ________ */
  'titleBar.activeBackground': editorColors.actBg,
  'titleBar.activeForeground': color.lightGray,
  'titleBar.inactiveBackground': editorColors.actBg,
  'titleBar.inactiveForeground': color.darkGray,
  'titleBar.border': color.darkGray + '70',

  /* ________ menu bar colors ________ */
  'menubar.selectionForeground': color.lightGray,
  'menubar.selectionBackground': shades.shade400,
  'menu.selectionBorder': shades.transparent,
  'menu.foreground': color.darkGray,
  'menu.background': shades.shade400,
  'menu.selectionForeground': color.lightGray,
  'menu.selectionBackground': shades.shade800,
  // "menu.selectionBorder": '',
  'menu.separatorBackground': color.darkGray,
  'menu.border': color.darkGray + '30',

  /* ________ command center colors ________ */
  // "commandCenter.foreground": '',
  // "commandCenter.activeForeground": '',
  // "commandCenter.background": '',
  // "commandCenter.activeBackground": '',
  // "commandCenter.border": '',
  // "commandCenter.inactiveForeground": '',
  // "commandCenter.inactiveBorder": '',

  /* ________ notifications colors ________ */
  'notificationCenter.border': color.darkGray + '70',
  'notificationCenterHeader.foreground': color.lightGray,
  'notificationCenterHeader.background': editorColors.actBg,
  // "notificationToast.border": '',
  'notifications.foreground': color.lightGray,
  'notifications.background': shades.shade400,
  'notifications.border': color.darkGray + '70',
  'notificationLink.foreground': color.red,
  'notificationsErrorIcon.foreground': color.red,
  'notificationsWarningIcon.foreground': color.yellow,
  'notificationsInfoIcon.foreground': color.blue,

  /* ________ banner colors ________ */
  // "banner.background": '',
  // "banner.foreground": '',
  // "banner.iconForeground": '',

  /* ________ extension colors ________ */
  // "extensionButton.prominentForeground": '',
  // "extensionButton.prominentBackground": '',
  // "extensionButton.prominentHoverBackground": '',
  // "extensionButton.background": '',
  // "extensionButton.foreground": '',
  // "extensionButton.hoverBackground": '',
  // "extensionButton.separator": '',
  // "extensionBadge.remoteBackground": '',
  // "extensionBadge.remoteForeground": '',
  // "extensionIcon.starForeground": '',
  // "extensionIcon.verifiedForeground": '',
  // "extensionIcon.preReleaseForeground": '',
  // "extensionIcon.sponsorForeground": '',

  /* ________ quick picker colors ________ */
  'pickerGroup.border': shades.shade100,
  'pickerGroup.foreground': color.red,
  // "quickInput.background": '',
  'quickInput.foreground': color.darkGray,
  'quickInputList.focusBackground': shades.shade800,
  'quickInputList.focusForeground': color.lightGray,
  // "quickInputList.focusIconForeground": '',
  // "quickInputTitle.background": '',

  /* ________ keybinding label colors ________ */
  // "keybindingLabel.background": '',
  // "keybindingLabel.foreground": '',
  // "keybindingLabel.border": '',
  // "keybindingLabel.bottomBorder": '',

  /* ________ keyboard shortcut table colors ________ */
  // "keybindingTable.headerBackground": '',
  // "keybindingTable.rowsBackground": '',

  /* ________ integrated terminal colors ________ */
  // "terminal.background": '',
  'terminal.border': color.darkGray,
  'terminal.foreground': color.lightGray,
  'terminal.ansiBlack': color.darkGray,
  'terminal.ansiBlue': color.blue,
  'terminal.ansiBrightBlack': color.gray,
  'terminal.ansiBrightBlue': color.blue,
  'terminal.ansiBrightCyan': color.sky,
  'terminal.ansiBrightGreen': color.teal,
  'terminal.ansiBrightMagenta': color.pink,
  'terminal.ansiBrightRed': color.brightRed,
  'terminal.ansiBrightWhite': color.white,
  'terminal.ansiBrightYellow': color.orange,
  'terminal.ansiCyan': color.cyan,
  'terminal.ansiGreen': color.teal,
  'terminal.ansiMagenta': color.purple,
  'terminal.ansiRed': color.red,
  'terminal.ansiWhite': color.lightGray,
  'terminal.ansiYellow': color.yellow,
  'terminal.selectionBackground': color.red + '33',
  'terminalCursor.foreground': color.lightGray,
  // "terminal.selectionForeground": '',
  // "terminal.inactiveSelectionBackground": '',
  // "terminal.findMatchBackground": '',
  // "terminal.findMatchBorder": '',
  // "terminal.findMatchHighlightBackground": '',
  // "terminal.findMatchHighlightBorder": '',
  'terminalCursor.background': color.red,
  // "terminalCursor.foreground": '',
  // "terminal.dropBackground": '',
  // "terminal.tab.activeBorder": '',
  // "terminalCommandDecoration.defaultBackground": '',
  // "terminalCommandDecoration.successBackground": '',
  // "terminalCommandDecoration.errorBackground": '',
  // "terminalOverviewRuler.cursorForeground": '',
  // "terminalOverviewRuler.findMatchForeground": '',

  /* ________ debug colors ________ */
  'debugToolBar.background': shades.shade400,
  'debugToolBar.border': color.darkGray + '70',
  // "editor.stackFrameHighlightBackground": '',
  // "editor.focusedStackFrameHighlightBackground": '',
  // "editor.inlineValuesForeground": '',
  // "editor.inlineValuesBackground": '',
  // "debugView.exceptionLabelForeground": '',
  // "debugView.exceptionLabelBackground": '',
  // "debugView.stateLabelForeground": '',
  // "debugView.stateLabelBackground": '',
  // "debugView.valueChangedHighlight": '',
  // "debugTokenExpression.name": '',
  // "debugTokenExpression.value": '',
  // "debugTokenExpression.string": '',
  // "debugTokenExpression.boolean": '',
  // "debugTokenExpression.number": '',
  // "debugTokenExpression.error": '',

  /* ________ testing colors ________ */
  // "testing.iconFailed": '',
  // "testing.iconErrored": '',
  // "testing.iconPassed": '',
  // "testing.runAction": '',
  // "testing.iconQueued": '',
  // "testing.iconUnset": '',
  // "testing.iconSkipped": '',
  // "testing.peekBorder": '',
  // "testing.peekHeaderBackground": '',
  // "testing.message.error.decorationForeground": '',
  // "testing.message.error.lineBackground": '',
  // "testing.message.info.decorationForeground": '',
  // "testing.message.info.lineBackground": '',

  /* ________ welcome page colors ________ */

  // "welcomePage.background": '',
  // "welcomePage.progress.background": '',
  // "welcomePage.progress.foreground": '',
  // "welcomePage.tileBackground": '',
  // "welcomePage.tileHoverBackground": '',
  // "welcomePage.tileShadow": '',
  'walkThrough.embeddedEditorBackground': editorColors.actBg,

  // "welcomePage.buttonHoverBackground": color.cyan, [deprecated, maybe]

  /* ________ source control colors ________ */
  // "scm.providerBorder": '',

  /* ________ git colors ________ */
  'gitDecoration.addedResourceForeground': color.teal,
  'gitDecoration.modifiedResourceForeground': color.yellow,
  'gitDecoration.deletedResourceForeground': color.red,
  // "gitDecoration.renamedResourceForeground": '',
  'gitDecoration.stageModifiedResourceForeground': color.orange,
  'gitDecoration.stageDeletedResourceForeground': color.orange,
  'gitDecoration.untrackedResourceForeground': color.green,
  'gitDecoration.ignoredResourceForeground': color.darkGray,
  'gitDecoration.conflictingResourceForeground': color.sky,
  'gitDecoration.submoduleResourceForeground': color.blue,

  /* ________ settings editor colors ________ */
  // 'settings.headerForeground': color.lightGray,
  // 'settings.modifiedItemIndicator': color.red,
  // 'settings.dropdownBackground': shades.shade800,
  // 'settings.dropdownForeground': color.lightGray,
  // 'settings.dropdownBorder': color.darkGray,
  // 'settings.dropdownListBorder': shades.transparent,
  // 'settings.checkboxBackground': shades.shade800,
  // "settings.checkboxForeground": '',
  // "settings.checkboxBorder": '',
  // 'settings.rowHoverBackground': shades.shade400,
  // "settings.textInputBackground": '',
  // "settings.textInputForeground": '',
  // "settings.textInputBorder": '',
  // "settings.numberInputBackground": '',
  // "settings.numberInputForeground": '',
  // "settings.numberInputBorder": '',
  // 'settings.focusedRowBackground': shades.shade800,
  // 'settings.focusedRowBorder': shades.transparent,
  // "settings.headerBorder": '',
  // "settings.sashBorder": '',

  /* ________ breadcrumbs colors ________ */
  'breadcrumb.foreground': color.darkGray,
  'breadcrumb.background': editorColors.editorBG,
  'breadcrumb.focusForeground': color.lightGray,
  'breadcrumb.activeSelectionForeground': color.lightGray,
  // "breadcrumbPicker.background": '',

  /* ________ snippets colors ________ */
  // "editor.snippetTabstopHighlightBackground": '',
  // "editor.snippetTabstopHighlightBorder": '',
  // "editor.snippetFinalTabstopHighlightBackground": '',
  // "editor.snippetFinalTabstopHighlightBorder": '',

  /* ________ symbol icons colors ________ */
  // "symbolIcon.arrayForeground": '',
  // "symbolIcon.booleanForeground": '',
  // "symbolIcon.classForeground": '',
  // "symbolIcon.colorForeground": '',
  // "symbolIcon.constantForeground": '',
  // "symbolIcon.constructorForeground": '',
  // "symbolIcon.enumeratorForeground": '',
  // "symbolIcon.enumeratorMemberForeground": '',
  // "symbolIcon.eventForeground": '',
  // "symbolIcon.fieldForeground": '',
  // "symbolIcon.fileForeground": '',
  // "symbolIcon.folderForeground": '',
  // "symbolIcon.functionForeground": '',
  // "symbolIcon.interfaceForeground": '',
  // "symbolIcon.keyForeground": '',
  // "symbolIcon.keywordForeground": '',
  // "symbolIcon.methodForeground": '',
  // "symbolIcon.moduleForeground": '',
  // "symbolIcon.namespaceForeground": '',
  // "symbolIcon.nullForeground": '',
  // "symbolIcon.numberForeground": '',
  // "symbolIcon.objectForeground": '',
  // "symbolIcon.operatorForeground": '',
  // "symbolIcon.packageForeground": '',
  // "symbolIcon.propertyForeground": '',
  // "symbolIcon.referenceForeground": '',
  // "symbolIcon.snippetForeground": '',
  // "symbolIcon.stringForeground": '',
  // "symbolIcon.structForeground": '',
  // "symbolIcon.textForeground": '',
  // "symbolIcon.typeParameterForeground": '',
  // "symbolIcon.unitForeground": '',
  // "symbolIcon.variableForeground": '',

  /* ________ debug icons colors ________ */
  // "debugIcon.breakpointForeground": '',
  // "debugIcon.breakpointDisabledForeground": '',
  // "debugIcon.breakpointUnverifiedForeground": '',
  // "debugIcon.breakpointCurrentStackframeForeground": '',
  // "debugIcon.breakpointStackframeForeground": '',
  // "debugIcon.startForeground": '',
  // "debugIcon.pauseForeground": '',
  // "debugIcon.stopForeground": '',
  // "debugIcon.disconnectForeground": '',
  // "debugIcon.restartForeground": '',
  // "debugIcon.stepOverForeground": '',
  // "debugIcon.stepIntoForeground": '',
  // "debugIcon.stepOutForeground": '',
  // "debugIcon.continueForeground": '',
  // "debugIcon.stepBackForeground": '',
  // "debugConsole.infoForeground": '',
  // "debugConsole.warningForeground": '',
  // "debugConsole.errorForeground": '',
  // "debugConsole.sourceForeground": '',
  // "debugConsoleInputIcon.foreground": '',

  /* ________ notebook colors ________ */
  // "notebook.editorBackground": '',
  // "notebook.cellBorderColor": '',
  // "notebook.cellHoverBackground": '',
  // "notebook.cellInsertionIndicator": '',
  // "notebook.cellStatusBarItemHoverBackground": '',
  // "notebook.cellToolbarSeparator": '',
  // "notebook.cellEditorBackground": '',
  // "notebook.focusedCellBackground": '',
  // "notebook.focusedCellBorder": '',
  // "notebook.focusedEditorBorder": '',
  // "notebook.inactiveFocusedCellBorder": '',
  // "notebook.inactiveSelectedCellBorder": '',
  // "notebook.outputContainerBackgroundColor": '',
  // "notebook.outputContainerBorderColor": '',
  // "notebook.selectedCellBackground": '',
  // "notebook.selectedCellBorder": '',
  // "notebook.symbolHighlightBackground": '',
  // "notebookScrollbarSlider.activeBackground": '',
  // "notebookScrollbarSlider.background": '',
  // "notebookScrollbarSlider.hoverBackground": '',
  // "notebookStatusErrorIcon.foreground": '',
  // "notebookStatusRunningIcon.foreground": '',
  // "notebookStatusSuccessIcon.foreground": '',

  /* ________ chart colors ________ */
  // "charts.foreground": '',
  // "charts.lines": '',
  // "charts.red": '',
  // "charts.blue": '',
  // "charts.yellow": '',
  // "charts.orange": '',
  // "charts.green": '',
  // "charts.purple": '',

  /* ________ ports colors ________ */
  // "ports.iconRunningProcessForeground": '',
};
