editorColors = {
  white: '#C9D6Da',
  red: '#E5736B',
  darkerWhite: '#617d8a',
  actBg: '#193036',
  ghostText: '#376D7A',
  selection: '#283845',
  shadow: '#17252a',
  btn2bg: '#38494d',
  btn2hover: '#455a64',
  editorBg: '#0F1923',
};

const lighten = (color, transparency) => {
  return color + transparency.toString(16);
};

module.exports = {
  'editorGhostText.foreground': editorColors.ghostText,
  foreground: editorColors.white,
  focusBorder: editorColors.darkerWhite,
  'progressBar.background': editorColors.darkerWhite,
  'selection.background': editorColors.selection,
  'scrollbar.shadow': editorColors.shadow,
  'activityBar.foreground': editorColors.white,
  'activityBar.background': editorColors.actBg,
  'activityBar.inactiveForeground': editorColors.darkerWhite,
  'activityBarBadge.foreground': editorColors.white,
  'activityBarBadge.background': editorColors.red,
  'button.background': lighten(editorColors.red, 220),
  'button.foreground': editorColors.white,
  'button.hoverBackground': editorColors.red,
  'textLink.foreground': lighten(editorColors.red, 220),
  'textLink.activeForeground': editorColors.red,
  'button.secondaryForeground': editorColors.white,
  'button.secondaryBackground': editorColors.btn2bg,
  'button.secondaryHoverBackground': editorColors.btn2hover,
  'editor.foreground': editorColors.white,
  'editor.background': editorColors.editorBg,
  'editorLineNumber.foreground': editorColors.darkerWhite,
  'editorLineNumber.activeForeground': editorColors.red,
  'editorCursor.foreground': editorColors.red,
  'editorCursor.background': editorColors.white,
  'editor.selectionBackground': editorColors.selection,
  'editor.inactiveSelectionBackground': lighten(
    editorColors.selection,
    127
  ),
  'editorWhitespace.foreground': lighten(editorColors.white, 102),
  'editor.selectionHighlightBackground': lighten(
    editorColors.red,
    72
  ),
  'editor.selectionHighlightBorder': editorColors.red,
  'editor.findMatchBackground': lighten(editorColors.red, 72),
  'editor.findMatchBorder': editorColors.red,
  'editor.findMatchHighlightBackground': lighten(
    editorColors.red,
    102
  ),
  'editor.findRangeHighlightBackground': '#000d0c33',
  'editor.rangeHighlightBackground': '#1e3242',
  'editor.hoverHighlightBackground': lighten(editorColors.red, 64),
  'editor.wordHighlightStrongBackground': lighten(
    editorColors.red,
    64
  ),
  'editor.wordHighlightBackground': lighten(editorColors.red, 72),
  'editor.wordHighlightStrongBorder': editorColors.red,
  'editor.lineHighlightBackground': '#182835',
  'editorLink.activeForeground': '#00bcd4',
  'editorIndentGuide.background': editorColors.darkerWhite,
  'editorIndentGuide.activeBackground': editorColors.white,
  'editorRuler.foreground': editorColors.darkerWhite,
  'editorBracketMatch.background': lighten(editorColors.red, 102),
  'editorBracketMatch.border': editorColors.red,
  'editor.foldBackground': '#1e3242',
  'editorOverviewRuler.border': '#617d8a66',
  'editorError.foreground': '#e57373',
  'editorWarning.foreground': '#ffb74d',
  'editorInfo.foreground': '#4fc3f7',
  'editorGutter.background': editorColors.editorBg,
  'editorGutter.addedBackground': '#82C781',
  'editorGutter.modifiedBackground': '#e5b965',
  'editorGutter.deletedBackground': '#e57373',
  'editorGutter.foldingControlForeground': editorColors.darkerWhite,
  'editorGutter.foldingControlHoverForeground': editorColors.white,
  'editorCodeLens.foreground': editorColors.darkerWhite,
  'editorGroup.border': editorColors.darkerWhite,
  'editorGroupHeader.border': '#00000000',
  'diffEditor.insertedTextBackground': '#43a04733',
  'diffEditor.removedTextBackground': '#e5393533',
  'diffEditor.border': editorColors.darkerWhite,
  'editorMarkerNavigation.background': editorColors.actBg,
  'editorMarkerNavigationError.background': '#e57373',
  'editorMarkerNavigationWarning.background': '#ffd54f',
  'editorMarkerNavigationInfo.background': '#4fc3f7',
  'merge.currentHeaderBackground': '#00897b',
  'merge.currentContentBackground': '#00695c',
  'merge.incomingHeaderBackground': '#00acc1',
  'merge.incomingContentBackground': '#00838f',
  'merge.commonHeaderBackground': '#546e7a',
  'merge.commonContentBackground': '#37474f',
  'editorSuggestWidget.background': '#172734',
  'editorSuggestWidget.border': '#617d8a70',
  'editorSuggestWidget.foreground': editorColors.darkerWhite,
  'editorSuggestWidget.highlightForeground': editorColors.red,
  'editorSuggestWidget.selectedBackground': '#1e3242',
  'editorHoverWidget.foreground': editorColors.darkerWhite,
  'editorHoverWidget.background': '#172734',
  'editorHoverWidget.border': '#617d8a70',
  'peekView.border': editorColors.darkerWhite,
  'peekViewEditor.background': '#262d38',
  'peekViewEditorGutter.background': '#262d38',
  'peekViewEditor.matchHighlightBackground': lighten(
    editorColors.red,
    102
  ),
  'peekViewEditor.matchHighlightBorder': editorColors.red,
  'peekViewResult.background': '#172734',
  'peekViewResult.fileForeground': editorColors.darkerWhite,
  'peekViewResult.lineForeground': editorColors.darkerWhite,
  'peekViewResult.matchHighlightBackground': lighten(
    editorColors.red,
    102
  ),
  'peekViewResult.selectionBackground': '#1e3242',
  'peekViewResult.selectionForeground': editorColors.white,
  'peekViewTitle.background': '#172734',
  'peekViewTitleDescription.foreground': editorColors.darkerWhite,
  'peekViewTitleLabel.foreground': editorColors.white,
  'widget.shadow': '#0b181e66',
  'editorWidget.foreground': editorColors.white,
  'editorWidget.background': '#172734',
  'pickerGroup.border': '#3f3f46',
  'pickerGroup.foreground': editorColors.red,
  'editorWidget.resizeBorder': editorColors.red,
  'debugToolBar.background': '#172734',
  'debugToolBar.border': '#617d8a70',
  'notifications.foreground': editorColors.white,
  'notifications.background': '#172734',
  'notifications.border': '#617d8a70',
  'notificationLink.foreground': editorColors.red,
  'notificationsErrorIcon.foreground': '#ff8a65',
  'notificationsWarningIcon.foreground': '#ffd54f',
  'notificationsInfoIcon.foreground': '#4fc3f7',
  'notificationCenterHeader.foreground': editorColors.white,
  'notificationCenterHeader.background': editorColors.actBg,
  'notificationCenter.border': '#617d8a70',
  'sideBar.background': '#132430',
  'sideBar.foreground': editorColors.darkerWhite,
  'sideBarSectionHeader.background': editorColors.actBg,
  'sideBarSectionHeader.foreground': editorColors.white,
  'sideBarSectionHeader.border': '#C9D6Da15',
  'sideBarTitle.foreground': editorColors.white,
  'list.inactiveSelectionBackground': '#1E3242',
  'list.inactiveSelectionForeground': '#95aab4',
  'list.hoverForeground': editorColors.white,
  'list.hoverBackground': '#00000000',
  'list.activeSelectionBackground': '#1E3242',
  'list.activeSelectionForeground': editorColors.white,
  'list.dropBackground': '#151f24',
  'list.highlightForeground': editorColors.white,
  'list.focusBackground': '#1e3242',
  'list.focusForeground': editorColors.white,
  'list.focusOutline': '#00000000',
  'listFilterWidget.background': editorColors.white,
  'listFilterWidget.noMatchesOutline': editorColors.red,
  'tree.indentGuidesStroke': editorColors.darkerWhite,
  'statusBar.foreground': editorColors.white,
  'statusBar.background': editorColors.editorBg,
  'statusBar.border': '#617d8a70',
  'statusBarItem.hoverBackground': '#C9D6Da33',
  'statusBar.debuggingBackground': '#ed8484',
  'statusBar.debuggingForeground': '#f2f2f2',
  'statusBar.noFolderBackground': '#84a7ed',
  'statusBar.noFolderForeground': '#f2f2f2',
  'statusBarItem.remoteBackground': editorColors.actBg,
  'statusBarItem.remoteForeground': editorColors.white,
  'titleBar.activeBackground': editorColors.actBg,
  'titleBar.activeForeground': editorColors.white,
  'titleBar.border': '#617d8a70',
  'titleBar.inactiveBackground': editorColors.actBg,
  'titleBar.inactiveForeground': editorColors.darkerWhite,
  'menubar.selectionForeground': editorColors.white,
  'menubar.selectionBackground': '#172734',
  'menu.foreground': editorColors.darkerWhite,
  'menu.background': '#172734',
  'menu.selectionForeground': editorColors.white,
  'menu.selectionBackground': '#1e3242',
  'menu.selectionBorder': '#00000000',
  'menu.separatorBackground': editorColors.darkerWhite,
  'menu.border': '#617d8a30',
  'quickInput.foreground': editorColors.darkerWhite,
  'quickInputList.focusBackground': '#1e3242',
  'quickInputList.focusForeground': editorColors.white,
  'input.background': '#1e3242',
  'input.foreground': editorColors.white,
  'input.placeholderForeground': editorColors.darkerWhite,
  'inputOption.activeBackground': editorColors.darkerWhite,
  'inputOption.activeForeground': editorColors.white,
  'checkbox.border': editorColors.red,
  'checkbox.foreground': editorColors.red,
  'panel.background': editorColors.editorBg,
  'panel.border': editorColors.darkerWhite,
  'panelTitle.activeBorder': editorColors.red,
  'panelTitle.activeForeground': editorColors.white,
  'panelTitle.inactiveForeground': editorColors.darkerWhite,
  'terminal.selectionBackground': '#E5736B33',
  'terminalCursor.foreground': editorColors.white,
  'terminalCursor.background': editorColors.red,
  'badge.background': editorColors.red,
  'badge.foreground': editorColors.white,
  'terminal.border': editorColors.darkerWhite,
  'terminal.foreground': editorColors.white,
  'terminal.ansiWhite': '#cfd8dc',
  'terminal.ansiBrightWhite': '#eceff1',
  'terminal.ansiBlack': '#78909c',
  'terminal.ansiBrightBlack': '#90a4ae',
  'terminal.ansiBlue': '#4fc3f7',
  'terminal.ansiBrightBlue': '#29b6f6',
  'terminal.ansiCyan': '#26c6da',
  'terminal.ansiBrightCyan': '#80deea',
  'terminal.ansiGreen': '#82C781',
  'terminal.ansiBrightGreen': '#82C781',
  'terminal.ansiMagenta': '#e040fb',
  'terminal.ansiBrightMagenta': '#ea80fc',
  'terminal.ansiRed': '#f44336',
  'terminal.ansiBrightRed': '#ef5350',
  'terminal.ansiYellow': '#ff9800',
  'terminal.ansiBrightYellow': '#ffb74d',
  'editorGroupHeader.tabsBackground': '#0e1720',
  'editorGroupHeader.tabsBorder': '#00000000',
  'tab.activeForeground': editorColors.white,
  'tab.activeBackground': editorColors.editorBg,
  'tab.activeBorderTop': editorColors.red,
  'tab.inactiveBackground': '#172734',
  'tab.inactiveForeground': editorColors.darkerWhite,
  'tab.hoverForeground': editorColors.white,
  'breadcrumb.background': editorColors.editorBg,
  'breadcrumb.foreground': editorColors.darkerWhite,
  'breadcrumb.focusForeground': editorColors.white,
  'scrollbarSlider.background': '#E5736B33',
  'scrollbarSlider.hoverBackground': lighten(editorColors.red, 102),
  'scrollbarSlider.activeBackground': '#E5736B99',
  'gitDecoration.addedResourceForeground': '#82C781',
  'gitDecoration.conflictingResourceForeground': '#73bae5',
  'gitDecoration.deletedResourceForeground': '#e57373',
  'gitDecoration.ignoredResourceForeground': '#78909c',
  'gitDecoration.modifiedResourceForeground': '#e5b965',
  'gitDecoration.stageDeletedResourceForeground': '#ff8a65',
  'gitDecoration.stageModifiedResourceForeground': '#ffb74d',
  'gitDecoration.submoduleResourceForeground': '#4fc3f7',
  'gitDecoration.untrackedResourceForeground': '#4db6ac',
  'settings.headerForeground': editorColors.white,
  'settings.modifiedItemIndicator': editorColors.red,
  'settings.dropdownBackground': '#1e3242',
  'settings.dropdownForeground': editorColors.white,
  'settings.dropdownBorder': editorColors.darkerWhite,
  'settings.dropdownListBorder': '#00000000',
  'settings.checkboxBackground': '#1e3242',
  'settings.rowHoverBackground': '#172734',
  'settings.focusedRowBackground': '#162025',
  'settings.focusedRowBorder': '#00000000',
  'minimapGutter.addedBackground': '#82C781',
  'minimapGutter.deletedBackground': '#e57373',
  'minimapGutter.modifiedBackground': '#73bae5',
  'walkThrough.embeddedEditorBackground': editorColors.actBg,
  'textPreformat.foreground': editorColors.white,
  'textBlockQuote.border': editorColors.darkerWhite,
  'welcomePage.buttonHoverBackground': '#11cbc0',
  'editorBracketHighlight.foreground1': '#e57373',
  'editorBracketPairGuide.activeBackground1': '#e57373',
  'editorBracketHighlight.foreground2': '#C792CD',
  'editorBracketPairGuide.activeBackground2': '#C792CD',
  'editorBracketHighlight.foreground3': '#73bae5',
  'editorBracketPairGuide.activeBackground3': '#73bae5',
  'editorBracketHighlight.foreground4': '#e5b965',
  'editorBracketPairGuide.activeBackground4': '#e5b965',
  'editorBracketHighlight.foreground5': '#82C781',
  'editorBracketPairGuide.activeBackground5': '#82C781',
  'editorBracketHighlight.foreground6': '#e89e30',
  'editorBracketPairGuide.activeBackground6': '#e89e30',
  'list.focusHighlightForeground': editorColors.red,
  'toolbar.hoverBackground': '#C9D6Da11',
  'toolbar.activeBackground': editorColors.red,
  'icon.foreground': editorColors.white,
  'dropdown.background': '#1e3242',
  'dropdown.foreground': editorColors.white,
  'dropdown.border': '#617d8a70',
  'minimap.background': editorColors.editorBg,
  'statusBarItem.activeBackground': editorColors.red,
  'breadcrumb.activeSelectionForeground': editorColors.white,
  'debugExceptionWidget.border': '#617d8a70',
  'debugExceptionWidget.background': '#172734',
};
